# Generated by Django 2.2 on 2019-12-12 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='video',
        ),
    ]
